### ISSUE TITLE
Tab Text Positioning Bug

### ISSUE THREAD

**Issue by okonomiyaki3000** [wyze/seti-icons#10]
I just updated to version 0.4.3 and the positioning of text on my tabs is all messed up. All text is positioned maybe 1em or more above where it should be (meaning it's mostly off screen). This seems to happen with any ui theme. Disabling seti-icons fixes the problem. It did not happen before updating to version 0.4.3.

**Comment by wyze** [comment]
Odd I didn't catch this multiple times while refreshing.. Looking at it now. I will have a fix out tonight!

Thanks.

**Comment by wyze** [comment]
I had a merge #7 that wasn't pulled locally yet and I had to pull it in before doing the release and it broke everything. I apologize for this, but when I tested before merging through GitHub, it all looked fine. :(

Published v0.4.4 that will remedy this.

**Comment by okonomiyaki3000** [comment]
Looks good now, thanks!
