### ISSUE TITLE
icon/text spacing (.html)

### ISSUE THREAD

**Issue by okonomiyaki3000** [wyze/seti-icons#12]
Compared with other file types, there is very little space between the HTML5 icon and the text of the file name. Such that the sidebar looks something like:

:boar:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;GruntFile.js
:beginner: index.html
:arrow_down:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;README.md

**Comment by wyze** [comment]
It looks okay to me. What theme are you using?

<img width="147" alt="screen shot 2015-09-03 at 6 20 06 pm" src="https://cloud.githubusercontent.com/assets/186971/9673297/81029f68-5268-11e5-96ee-39c117bb0db5.png">

**Comment by okonomiyaki3000** [comment]
Hmm. You're right, other themes seem to be OK. I'm using 'Atom Material'. It seems to be something about how seti-icons interacts with that particular theme because disabling either the theme or the icons plugin fixes the issue.

**Comment by wyze** [comment]
Okay. I see it now. There is a `Compact Tree View` option for `Atom Material`. With it disabled, the icons look normal, but enabled. I see what you are seeing. I'll see what can be done.

**Comment by wyze** [comment]
I just published v0.4.5 that has a fix for this.

**Comment by okonomiyaki3000** [comment]
Thank you!
