### ISSUE TITLE
Wrong icons for css and html (maybe more file types also)

### ISSUE THREAD

**Issue by Nosenation** [wyze/seti-icons#3]
Hi
I just installed you package and I like it, but I have one problem. For .html and .css file I see wrong icons (different one than from Seti UI). Problem may also appear on different file types.

Screen: 
![zrzut ekranu 2015-06-29 o 22 21 11](https://cloud.githubusercontent.com/assets/1431712/8417516/7bf37360-1ead-11e5-8dbf-053845f93bd7.png)

**Comment by wyze** [comment]
The HTML and CSS icons were updated recently to point to newer versions HTML5/CSS3. I can look at adding an option in the future to choose which one to load.

**Comment by Nosenation** [comment]
I think that you should just make it 1:1 with Seti current icons. Nothing more, besides you show wrong icons to ppl in plugin readme file (https://raw.githubusercontent.com/jesseweed/seti-ui/master/screenshot.png).

**Comment by JoeWells** [comment]
+1

**Comment by wyze** [comment]
I have added a new configuration option to load enhanced/additional icons. This is false by default. If left off, you will have 1:1 with Seti UI theme.

This was added in 0.4.0.
