### ISSUE TITLE
Support variants for extensions (.htm and not only .html) 

### ISSUE THREAD

**Issue by 3ffy** [wyze/seti-icons#4]
Hi it would be great if your plugin could natively handle common variant file extensions : 

- it's case sensitive :( (.HTML won't be supported when .html is)

- Some language got multiples possible files extensions (i don't decide who made the project, so i have to use files like they are ^^'... (.htm won't be supported when .html is, i assume it's the same with .php5, .php4, .jpeg, etc.). 

It would be nice to include (at least) these ones !

**Comment by wyze** [comment]
The `.jpeg` extension is already handled.

**Comment by wyze** [comment]
I am adding the `.php4` and `.php5` extensions.

**Comment by wyze** [comment]
I also added `.HTML` and `.htm`/`.HTM`. I want to find a better way to handle the different extensions though.

**Comment by wyze** [comment]
These have been published in v0.3.1.
