### ISSUE TITLE
Sidebar folder misalignment

### ISSUE THREAD

**Issue by okonomiyaki3000** [wyze/seti-icons#8]
If a folder in the sidebar is named with a file extension (e.g. :file_folder: less.js) the positioning of the folder icon will be slightly left of other folders that are not named in this way.

**Comment by okonomiyaki3000** [comment]
This is still a thing.

**Comment by wyze** [comment]
This was published in v0.4.4.

**Comment by okonomiyaki3000** [comment]
Great!
