### ISSUE TITLE
C file icon overlap

### ISSUE THREAD

**Issue by Tylerflick** [wyze/seti-icons#9]
C file icons are overlapping on the tab with the following config:
* UI Theme: Atom Material
* Syntax Theme: Seti
* Atom build: 1.0.7

![image](https://cloud.githubusercontent.com/assets/1302085/9429620/45b209de-498b-11e5-94ca-7fbbb1ef4917.png)

They appear fine on the tree view.

I've played around with the tab sizes, etc. and can't mitigate the issue.

**Comment by oviung** [comment]
Yea... The only way around it that I've found is to set the `Icons in tabs` option to only "Show on active tab".

**Comment by wyze** [comment]
Just published 0.4.3 with the fix included. It also respects the `Icons in tabs` settings.
